name: field_guide_vision
description: A project that takes image input and extracts and translates Arabic text to English.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  #Code added below is for Amazon Translate
  aws_translate_api: ^2.0.0
  shared_aws_api: ^2.0.1
  aws_client: ^0.4.1
  http: ^0.13.6
  #End of Amazon Translate code
  flutter_localizations:
    sdk: flutter
  
  #GPS
  geolocator: ^11.0.0
  permission_handler: ^11.0.1
  geocoding: ^3.0.0
  #http: ^0.13.6
  collection: ^1.15.0
  #End of GPS

  image_picker: ^1.0.7
  image_cropper: ^4.0.1
  image: ^4.1.3

  path: ^1.8.3
  path_provider: ^2.1.2
  googleapis: ^13.1.0
  googleapis_auth: ^1.4.1
  _discoveryapis_commons: ^1.0.6

  dcdg: ^4.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/c5isr.png
    - assets/images/vt-logo.png
    - assets/images/GoodExample1.png
    - assets/images/GoodExample2.png
    - assets/images/StraightImage.png
    - assets/images/TiltedImage.png
